// lib/seed-data.ts
export const zambianSubjects = {
  PRIMARY: [
    "English Language",
    "Mathematics",
    "Zambian Languages",
    "Social Studies",
    "Science",
    "Creative and Technology Studies",
    "Religious Education",
    "Physical Education",
  ],
  JUNIOR: [
    "English Language",
    "Mathematics",
    "Science",
    "Social Studies",
    "Zambian Languages",
    "French",
    "Religious Education",
    "Business Studies",
    "Computer Studies",
    "Home Economics",
    "Design and Technology",
    "Physical Education",
  ],
  SENIOR: [
    "English Language",
    "Mathematics",
    "Biology",
    "Chemistry",
    "Physics",
    "Geography",
    "History",
    "Civic Education",
    "Religious Education",
    "Commerce",
    "Principles of Accounts",
    "Computer Studies",
    "French",
    "Literature in English",
    "Food and Nutrition",
    "Fashion and Fabrics",
    "Woodwork",
    "Metalwork",
    "Technical Drawing",
    "Agricultural Science",
  ],
  COLLEGE: [
    "University of Zambia (UNZA)",
    "Copperbelt University (CBU)",
    "Mulungushi University",
    "Zambia Catholic University",
    "Zambian Open University (ZAOU)",
    "Evelyn Hone College",
    "Natural Resources Development College (NRDC)",
    "Northern Technical College (NORTEC)",
    "Lusaka Apex Medical University",
    "Cavendish University Zambia",
    "Rusangu University",
    "Zambia Centre for Accountancy Studies (ZCAS)",
    "David Livingstone College of Education",
    "Nkrumah University Teachers College",
  ],
};

export const zambianTeachers = [
  {
    name: "Dr. Chanda Bwalya",
    email: "chanda.bwalya@school.edu.zm",
    bio: "Senior Mathematics teacher with 15 years experience in Zambian curriculum",
    expertise: "Mathematics and Physics",
    qualifications: "M.Ed Mathematics, University of Zambia",
  },
  {
    name: "Mrs. Nkandu Mwamba",
    email: "nkandu.mwamba@school.edu.zm",
    bio: "English Language specialist with focus on Zambian context",
    expertise: "English Language and Literature",
    qualifications: "B.A Education English, UNZA",
  },
  {
    name: "Mr. Musonda Phiri",
    email: "musonda.phiri@school.edu.zm",
    bio: "Science teacher passionate about practical experiments",
    expertise: "Biology and Chemistry",
    qualifications: "B.Sc Education Biology, CBU",
  },
  {
    name: "Dr. Mulenga Tembo",
    email: "mulenga.tembo@college.edu.zm",
    bio: "University lecturer in Computer Science",
    expertise: "Programming and Data Structures",
    qualifications: "PhD Computer Science, University of Zambia",
  },
];

export const zambianClasses = [
  // PRIMARY LEVEL
  {
    id: "class_primary_1",
    title: "Grade 7 Comprehensive Revision",
    description:
      "Complete revision class for Grade 7 students covering all primary school subjects as per Zambian curriculum",
    level: "PRIMARY" as const,
    grade: "Grade 7",
    startsOn: new Date("2024-09-01"),
    endsOn: new Date("2024-12-15"),
    fee: 450,
    enrollmentStatus: "IN_PROGRESS" as const,
    subjects: ["English Language", "Mathematics", "Science", "Social Studies"],
    coverImage: "/images/primary-class.jpg",
  },

  // JUNIOR SECONDARY
  {
    id: "class_junior_1",
    title: "Junior Secondary Science Intensive",
    description:
      "Focus on Science subjects for Grades 8-9 students with practical experiments and ECZ exam preparation",
    level: "JUNIOR" as const,
    grade: "Grades 8-9",
    startsOn: new Date("2024-08-15"),
    endsOn: new Date("2024-11-30"),
    fee: 600,
    enrollmentStatus: "STARTING_SOON" as const,
    subjects: [
      "Science",
      "Mathematics",
      "English Language",
      "Computer Studies",
    ],
    coverImage: "/images/junior-science.jpg",
  },

  // SENIOR SECONDARY
  {
    id: "class_senior_1",
    title: "Grade 12 ECZ Examination Prep",
    description:
      "Comprehensive preparation for Grade 12 ECZ examinations with past paper practice and marking schemes",
    level: "SENIOR" as const,
    grade: "Grade 12",
    startsOn: new Date("2024-07-01"),
    endsOn: new Date("2024-10-31"),
    fee: 850,
    enrollmentStatus: "IN_PROGRESS" as const,
    subjects: [
      "Mathematics",
      "Biology",
      "Chemistry",
      "Physics",
      "English Language",
    ],
    coverImage: "/images/senior-exam-prep.jpg",
  },
  {
    id: "class_senior_2",
    title: "Commerce & Business Studies",
    description:
      "Specialized class for Commerce stream students focusing on Principles of Accounts and Business Studies",
    level: "SENIOR" as const,
    grade: "Grades 10-12",
    startsOn: new Date("2024-09-10"),
    endsOn: new Date("2025-01-20"),
    fee: 700,
    enrollmentStatus: "STARTING_SOON" as const,
    subjects: [
      "Commerce",
      "Principles of Accounts",
      "Business Studies",
      "Economics",
    ],
    coverImage: "/images/commerce-class.jpg",
  },

  // COLLEGE LEVEL
  {
    id: "class_college_1",
    title: "Introduction to Computer Programming",
    description:
      "University-level programming course covering Python, algorithms, and data structures for Zambian students",
    level: "COLLEGE" as const,
    grade: "First Year",
    startsOn: new Date("2024-08-01"),
    endsOn: new Date("2024-12-15"),
    fee: 1200,
    enrollmentStatus: "IN_PROGRESS" as const,
    subjects: ["Computer Science", "Programming", "Algorithms"],
    coverImage: "/images/college-programming.jpg",
  },
  {
    id: "class_college_2",
    title: "Business Management Fundamentals",
    description:
      "Essential business management concepts for college students and young entrepreneurs in Zambia",
    level: "COLLEGE" as const,
    grade: "All Levels",
    startsOn: new Date("2024-09-05"),
    endsOn: new Date("2024-11-20"),
    fee: 950,
    enrollmentStatus: "STARTING_SOON" as const,
    subjects: [
      "Business Administration",
      "Marketing",
      "Accounting",
      "Economics",
    ],
    coverImage: "/images/business-management.jpg",
  },
];
